Resources:
    RetryBillingParser:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python3.10
            CodeUri: .